// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7bKu24DAycWJoLb54H_0ouhPL1nJCaI8',
    appId: '1:456963269638:web:38cc75493f5f5490e50f87',
    messagingSenderId: '456963269638',
    projectId: 'e--commrece',
    authDomain: 'e--commrece.firebaseapp.com',
    storageBucket: 'e--commrece.firebasestorage.app',
    measurementId: 'G-Q7Z3N39B1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsn2wGs3UlefGmPHrEAMTWnSLFzdJgvGw',
    appId: '1:456963269638:android:220a6b88c9bed736e50f87',
    messagingSenderId: '456963269638',
    projectId: 'e--commrece',
    storageBucket: 'e--commrece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBqrpwJ6_0BRedbkHHDmCgk5BUJtfMtYI',
    appId: '1:456963269638:ios:65ff72014818bf7de50f87',
    messagingSenderId: '456963269638',
    projectId: 'e--commrece',
    storageBucket: 'e--commrece.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBqrpwJ6_0BRedbkHHDmCgk5BUJtfMtYI',
    appId: '1:456963269638:ios:65ff72014818bf7de50f87',
    messagingSenderId: '456963269638',
    projectId: 'e--commrece',
    storageBucket: 'e--commrece.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );
}
